### PR TITLE
Develop - allow users as rule destination 

### LINKED ISSUE #1535: cpr8x importer - handling access-roles in rule destination
example in rulebase mgm_id_1176_config_native.json.anon_error_in_fprs100-s999-rz99-xxx-PolicyNetwork.anon rule uid 6c1f27c8-5993-48a4-afc1-a312be8b6481

needs to be taken care of both in parser and stored procedure import (make it symmetrical for src and dst?)

```json
{
                  "destination": [
                    {
                      "uid": "eba4b14b-e30a-4927-b46b-c0c50c9a3bb3",
                      "name": "xxx_ras_users",
                      "type": "access-role",
                      "networks": [
                        "b3e8911a-6e14-481b-8966-e72b3f663e24"
                      ],
                      "users": [
                        "2530ad0d-6008-4827-a345-e7c9f2e20494"
                      ],
                      "remote-access-client": "97aeb369-9aea-11d5-bd16-0090272ccb30",
                    }
                  ]
}
```

### LINKED ISSUE #1541: importer CPR8x - need to match nat and access rulebases
This should be integrated with auto-discovery module 

error:
```
  File "/usr/local/fworch/importer/checkpointR8x/fwcommon.py", line 83, in get_config
    full_config['nat_rulebases'][rb_id], target_rulebase, full_config['rulebases'][rb_id]['layername'], current_import_id, rule_num, section_header_uids, parent_uid)
IndexError: list index out of range
```

roles/importer/files/importer/checkpointR8x/cpcommon.py
```
        # getting NAT rules - need package name for nat rule retrieval
        # todo: each gateway/layer should have its own package name (pass management details instead of single data?)
```

rulebases can have no nat rulebases at all - need to simply add empty nat rulebase then

roles/importer/files/importer/checkpointR8x/fwcommon.py
```python
            # parse nat rules
            if len(full_config['nat_rulebases'])>0:
                if len(full_config['nat_rulebases']) != len(rb_range):
                    logging.warning('get_config - found ' + str(len(full_config['nat_rulebases'])) +
                        ' nat rulebases and ' +  str(len(rb_range)) + ' rulebases')
                    # todo: need to match nat and access rulebases
```

### PR DESCRIPTION
**Pull request by tpurschke**
closes #1535
might also fix #1541

### CODE REVIEW

File: roles/database/files/sql/creation/fworch-create-tables.sql [hunk 1]
```diff
@@ -226,7 +226,6 @@ Create table "rule_user_resolved"
 
 Create table "rule_from"
 (
-	"rule_from_id" BIGSERIAL,
```
Comment (abarz722) [inline roles/database/files/sql/creation/fworch-create-tables.sql:229]: delete the primary key?

**Review by abarz722 — CHANGES_REQUESTED** [review]

**Review by abarz722 — APPROVED** [review]
