### PR TITLE
Develop Adding CP Domain UID

### LINKED ISSUE #1869: Importer/Autodiscovery - CP R81 MDS bug prevents login to domain
for one (broken CP MDS) installation we are not able to login to any domain (via its name) after upgrading the MDS

approach: make login work both via name or UID of domain (auto-recognize UID with pattern) 
```

[Expert@xxx:0]# cpinfo -y all
This is Check Point CPinfo Build 914000227 for GAIA

[MGMT]
        HOTFIX_R81_10_JHF_T66_972_MAIN
        HOTFIX_R81_10_JUMBO_HF_MAIN     Take:  66

FW1 build number:
This is Check Point Security Management Server R81.10 - Build 006
This is Check Point's software version R81.10 - Build 020

[SecurePlatform]
        HOTFIX_R81_10_JUMBO_HF_MAIN     Take:  66

[SFWR80CMP]
        HOTFIX_R81_10_JHF_COMP  Take:  66

[PROVIDER-1]
        HOTFIX_R81_10_JUMBO_HF_MAIN     Take:  66


Login top level works:

curl --request POST --insecure --url https://xxx/web_api/login --header 'content-type: application/json' --header 'Accept: application/json' --data ' { "user": "itsecorg", "password": "xxx"}'

{
  "uid" : "5a740ac3-5983-4947-821e-4eef4562fd9a",
  "sid" : "OVLvPgHU0akhUr0ogkf3MlDhqoYbhjOR0v7yfi-x2G8",
  "url" : "https://yyy:443/web_api",
  "session-timeout" : 600,
  "api-server-version" : "1.8",
  "user-name" : "itsecorg",
  "user-uid" : "914d343f-3eac-460f-90c7-f6d0852285e7"
}

 

Login with manager name fails:

curl --request POST --insecure --url https://yyy/web_api/login --header 'content-type: application/json' --header 'Accept: application/json' --data ' { "user": "itsecorg", "password": "xxx", "domain": "sckp011" '
{
  "code" : "err_login_failed",
  "message" : "Authentication to server failed."
}

 

Login with manager IP works:

curl --request POST --insecure --url https://yyy/web_api/login --header 'content-type: application/json' --header 'Accept: application/json' --data ' { "user": "itsecorg", "password": "xxx", "domain": "2.2.64.11" }'
{
  "sid" : "yv7wFo27MSARopMZ3LkYTowY9tYiY_ZTz0SJzHsf4hg",
  "url" : "https://yyy:443/web_api",
 "session-timeout" : 600,
 "read-only" : true,
 "api-server-version" : "1.8",
 "user-name" : "itsecorg",
 "user-uid" : "914d343f-3eac-460f-90c7-f6d0852285e7"
}

 

Login with domain uid works:

curl --request POST --insecure --url https://yyy/web_api/login --header 'content-type: application/json' --header 'Accept: application/json' --data ' { "user": "itsecorg", "password": "xxx", "domain": "cf7c1838-795d-8e4f-8469-8e053dff59be" }'
{
  "sid" : "EkVrB2-UB99JyDWKqdoO6pS_dEiPkgMlxzONGJEzvok",
  "url" : "https://yyy:443/web_api",
  "session-timeout" : 600,
  "read-only" : true,
  "api-server-version" : "1.8",
  "user-name" : "itsecorg",
  "user-uid" : "914d343f-3eac-460f-90c7-f6d0852285e7"
}

 

Login with domain name fails:

curl --request POST --insecure --url https://yyy/web_api/login --header 'content-type: application/json' --header 'Accept: application/json' --data ' { "user": "itsecorg", "password": "xxx", "domain": "Mgmt-Cluster_UK" }'

{
  "code" : "err_login_failed",
  "message" : "Authentication to server failed."
} 
```

### PR DESCRIPTION
**Pull request by tpurschke**
Work-around for bug #1869 
changes in 
- settings management
- auto disovery
- importer

closes #1869

### CODE REVIEW

File: roles/lib/files/FWO.DeviceAutoDiscovery/AutoDiscoveryCpMds.cs [hunk 1]
```diff
@@ -25,8 +25,10 @@ public override async Task<List<Management>> Run()
                 {
                     Log.WriteDebug("Autodiscovery", $"discovering CP domains & gateways");
                     CheckPointClient restClientCP = new CheckPointClient(superManagement);
-
-                    RestResponse<CpSessionAuthInfo> sessionResponse = await restClientCP.AuthenticateUser(superManagement.ImportCredential.ImportUser, superManagement.ImportCredential.Secret, superManagement.ConfigPath);
+                    string domainString = superManagement.ConfigPath;
+                    if (superManagement.DomainUid != null && superManagement.DomainUid != "")
+                        domainString= superManagement.ConfigPath;
```
Comment (abarz722) [inline roles/lib/files/FWO.DeviceAutoDiscovery/AutoDiscoveryCpMds.cs:30]: not DomainUid?

**Review by abarz722 — APPROVED** [review]
